name: slim4-project

services:
  # PHP 應用服務
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slim_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app_network
    depends_on:
      - mysql
      - redis
    command: >
      /bin/sh -c "
        composer update --no-interaction --no-progress --prefer-dist &&
        php-fpm
      "

  # Nginx 服務
  nginx:
    image: nginx:alpine
    container_name: slim_nginx
    restart: unless-stopped
    ports:
      - "8243:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./docker/nginx/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - app_network
    command: nginx -g 'daemon off;'

  # MySQL 服務
  mysql:
    image: mysql:8.0
    container_name: slim_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: mysql
      # 字元編碼設定
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
      TZ: Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - app_network

  # PHPMyAdmin 服務已移除，改用獨立下載的版本

  # Redis 服務
  redis:
    image: redis:alpine
    container_name: slim_redis
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - redis_data:/data
      
  # Loki - 日誌儲存和查詢引擎
  loki:
    image: grafana/loki:latest
    container_name: slim_loki
    restart: unless-stopped
    volumes:
      - loki_data:/loki
    environment:
      - LOKI_LIMITS_RETENTION_PERIOD=2160h
    networks:
      - app_network
    # 設定日誌保留策略為 90 天 (90 * 24 = 2160 小時)

  # Promtail - 日誌收集器
  promtail:
    image: grafana/promtail:latest
    container_name: slim_promtail
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/1f:ro  # 唯讀方式掛載日誌目錄
      - ./docker/promtail-config.yml:/etc/promtail/config.yml:ro  # 配置檔
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app_network
    depends_on:
      - loki

  # Grafana - 視覺化工具
  grafana:
    image: grafana/grafana:latest
    container_name: slim_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  # Grafana Web 介面
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=1fBreakfast2025
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - app_network
    depends_on:
      - loki

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  loki_data:
    driver: local
  grafana_data:
    driver: local