server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          app: web
          __path__: /var/log/nginx/nginx_*.log
    pipeline_stages:
      - json:
          expressions:
            remote_addr: remote_addr
            request_method: request_method
            request: request
            status: status
            body_bytes_sent: body_bytes_sent
            request_time: request_time
            http_referrer: http_referrer
            http_user_agent: http_user_agent
            uri: uri
            request_uri: request_uri
            query_string: query_string
            request_id: request_id
            http_x_forwarded_for: http_x_forwarded_for
            time_local: time_local
      - labels:
          remote_addr: remote_addr
          request_method: request_method
          status: status
          uri: uri
          app: app
          job: job

  - job_name: 1f_admin_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: 1fBreakFast
          app: admin
          __path__: /var/log/1f/admin_*.log
    pipeline_stages:
      - json:
          expressions:
            user_id: user_id
            username: username
            action: action
            target: target
            memo: memo
            ip_address: ip_address
            request_id: request_id
            timestamp: timestamp
      - labels:
          user_id: user_id
          action: action
          app: app
          job: job
      - labeldrop:
          - timestamp
