server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 1f_admin_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: 1fBreakFast
          app: admin
          __path__: /var/log/1f/admin_*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            user_id: user_id
            username: username
            action: action
            target: target
            memo: memo
            ip_address: ip_address
            request_id: request_id
      - labels:
          timestamp:
          user_id:
          username:
          action:
          target:
          memo:
          ip_address:
          request_id:
      # 移除時間戳記處理，使用系統時間
      - labeldrop:
          - timestamp
