server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          app: web
          __path__: /var/log/nginx/nginx_*.log
    pipeline_stages:
      - json:
          expressions:
            remote_addr: remote_addr
            remote_user: remote_user
            time_local: time_local
            request_method: request_method
            request: request
            status: status
            body_bytes_sent: body_bytes_sent
            request_time: request_time
            http_referer: http_referrer
            http_user_agent: http_user_agent
            http_x_forwarded_for: http_x_forwarded_for
            request_id: request_id
            uri: uri
            request_uri: request_uri
            query_string: query_string
      - labels:
          remote_addr:
          remote_user:
          time_local:
          request_method:
          request:
          status:
          body_bytes_sent:
          request_time:
          http_referer:
          http_user_agent:
          http_x_forwarded_for:
          request_id:
          uri:
          request_uri:
          query_string:

  - job_name: 1f_admin_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: 1fBreakFast
          app: admin
          __path__: /var/log/1f/admin_*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            user_id: user_id
            username: username
            action: action
            target: target
            memo: memo
            ip_address: ip_address
            request_id: request_id
      - labels:
          timestamp:
          user_id:
          username:
          action:
          target:
          memo:
          ip_address:
          request_id:
      # 移除時間戳記處理，使用系統時間
      - labeldrop:
          - timestamp
